---
# tasks file for jenkins
- name: Removing old version of Java from amazon linux
  yum:
   name: java-1.7.0-openjdk
   state: absent

- name: Install specific supported version of java
  yum: 
   name: java-1.8.0-openjdk
   state: present

- name: Add jenkins repository
  shell: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo

- name : Import Jenkins GPG Key
   rpm_key:
   key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
   state: present

- name: Install Jenkins
  yum:
   name: jenkins-2.99
   enablerepo: jenkins
   state: present

- name: Start jenkins
  service:
   name: jenkins
   enabled: yes
   state : started
